name: Build VSIX package

on:
  workflow_call:
    inputs:
      pre_release:
        description: 'Build as pre-release'
        type: boolean
        default: false
    outputs:
      vsix_path:
        description: 'Path to built VSIX file'
        value: ${{ jobs.build.outputs.vsix_path }}
      version:
        description: 'Version of built package'
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      vsix_path: ${{ steps.build.outputs.vsix_path }}
      version: ${{ steps.build.outputs.version }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
      - run: npm run compile

      - name: Set pre-release flag
        if: inputs.pre_release
        run: |
          # Add pre-release flag to package.json
          npm pkg set preview=true

      - name: Build VSIX
        id: build
        run: |
          npx vsce package
          VSIX_PATH=$(ls *.vsix)
          VERSION=$(node -p "require('./package.json').version")
          echo "vsix_path=${VSIX_PATH}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-extension
          path: '*.vsix'
