name: Publish extension

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        type: string
        required: true
      pre_release:
        description: 'Publish as pre-release'
        type: boolean
        default: false
  workflow_call:
    inputs:
      environment:
        description: 'Target environment'
        type: string
        required: true
      pre_release:
        description: 'Publish as pre-release'
        type: boolean
        default: false
    secrets:
      VSCE_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - name: Download VSIX artifact
        uses: actions/download-artifact@v4
        with:
          name: vscode-extension

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Publish to marketplace
        run: |
          if [ "${{ inputs.pre_release }}" = "true" ]; then
            vsce publish --pre-release -p ${{ secrets.VSCE_TOKEN }}
          else
            vsce publish -p ${{ secrets.VSCE_TOKEN }}
          fi
