name: Generate JSON Schema

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update-json-schema]

concurrency:
  group: generate-schema-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-pre-commit:
    uses: amp-labs/vs-code-extension/.github/workflows/pre-commit.yml@main

  generate-and-pr:
    needs: run-pre-commit
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log trigger event
        run: echo "Schema update triggered by ${{ github.event_name }} event"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install schema dependencies
        run: cd schemas && npm ci

      - name: Fetch latest manifest.json from OpenAPI repo
        run: |
          curl -o schemas/manifest.json https://raw.githubusercontent.com/amp-labs/openapi/refs/heads/main/manifest/generated/manifest.json

      - name: Build schema
        run: cd schemas && npm run generate

      - name: Check for changes
        id: check
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected in schema"
          fi

      - name: Create PR
        if: steps.check.outputs.changes == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Configure git
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

          # Create branch and commit
          BRANCH="update-manifest-schema-${{ github.run_number }}"
          git checkout -b "$BRANCH"
          git add .
          git commit -m "chore: update manifest JSON schema"
          git push origin "$BRANCH"

          # Verify GitHub CLI authentication
          echo "Verifying GitHub CLI authentication..."
          gh auth status

          # Create PR using GitHub CLI
          gh pr create \
            --title "Update manifest JSON schema" \
            --body "This PR updates the manifest JSON schema based on changes in the OpenAPI repository.

          - Source: ${{ github.event.client_payload.repository || 'amp-labs/openapi' }}
          - Triggered by: ${{ github.event.client_payload.sha || 'manual' }}
          - Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          **Please review carefully to ensure these changes don't break the VS Code extension.**" \
            --base main \
            --head "$BRANCH"
